//! MCP tool serving the plugin UI kit contract (`ui-kit/contract.json`,
//! compiled in) plus the live-resolved theme tokens.

use std::sync::LazyLock;

use rmcp::handler::server::wrapper::{Json, Parameters};
use rmcp::{ErrorData as McpError, tool, tool_router};
use serde_json::Value;

use crate::themes;

use super::SmabarMcp;
use super::types::{UiKitParams, UiKitResult};

const CONTRACT_JSON: &str = include_str!("../../../../ui-kit/contract.json");
/// The harvested component vocabulary, GENERATED by
/// `scripts/gen-kit-classes.py` from the format48 manifests.
const KIT_CLASSES_JSON: &str = include_str!("../../../../ui-kit/kit-classes.json");

fn parse(source: &str, what: &str) -> Value {
    serde_json::from_str(source).unwrap_or_else(|error| {
        // Unreachable in a healthy build: a test asserts the bundle parses.
        tracing::error!(%error, %what, "bundled ui-kit JSON is invalid");
        Value::Null
    })
}

static CONTRACT: LazyLock<Value> = LazyLock::new(|| parse(CONTRACT_JSON, "contract.json"));

/// smabar's own classes first, then the harvested component classes — one
/// list, because an agent asking for "classes" wants the whole vocabulary.
/// Every entry carries a `category`, which is what the category sections slice
/// on.
static CLASSES: LazyLock<Vec<Value>> = LazyLock::new(|| {
    let own = CONTRACT["classes"].as_array().cloned().unwrap_or_default();
    let kit = parse(KIT_CLASSES_JSON, "kit-classes.json");
    let harvested = kit["classes"].as_array().cloned().unwrap_or_default();
    own.into_iter().chain(harvested).collect()
});

/// One section per class category. Handing an agent 200+ classes at once is
/// worse than handing it none: it stops reading. These let it fetch the
/// vocabulary of the thing it is building.
pub(super) const CATEGORIES: &[&str] = &[
    "actions",
    "content",
    "data",
    "disclosure",
    "feedback",
    "forms",
    "layout",
    "overlays",
];

/// Every top-level contract key is a section of its own, so an agent that
/// needs charts asks for charts instead of guessing which neighbour carries
/// them.
pub(super) const SECTIONS: &[&str] = &[
    "all",
    "bestPractices",
    "coverLayouts",
    "snippets",
    "behaviour",
    "conventions",
    "sanitizer",
    "media",
    "formContract",
    "branding",
    "renderTargets",
    "tileChrome",
    "charts",
    "icons",
    "tokens",
    "classes",
];

/// Keys that also travel with a related section: the classes of a category
/// are useless without the contract that gives them meaning.
pub(super) const RIDERS: &[(&str, &[&str])] = &[
    ("charts", &["icons", "data"]),
    ("media", &["sanitizer", "content"]),
    ("formContract", &["sanitizer", "forms"]),
    ("branding", &["sanitizer", "conventions"]),
    ("renderTargets", &["conventions"]),
    ("tileChrome", &["conventions"]),
];

const MAX_SECTIONS: usize = 4;

fn known(section: &str) -> bool {
    SECTIONS.contains(&section) || CATEGORIES.contains(&section)
}

/// What `all` says about the behaviour layer.
///
/// The full entries are 10 KB — as much as the whole class vocabulary — so
/// every reply carries the index instead: what the layer is, the one rule
/// that trips agents up (state lives in the DOM), and one line per hook.
/// `sections=["behaviour"]` then serves the examples.
fn behaviour_index() -> Option<Value> {
    let behaviour = CONTRACT.get("behaviour")?;
    let hooks = behaviour.get("hooks")?.as_array()?;
    let summary: Vec<Value> = hooks
        .iter()
        .filter_map(|entry| {
            let hook = entry.get("hook")?.as_str()?;
            let what = entry.get("what")?.as_str()?;
            // The first sentence is the capability; the rest is the how,
            // which only matters once the agent asks for this hook.
            let head = what.split_once(". ").map_or(what, |(first, _)| first);
            Some(Value::String(format!("{hook} — {head}")))
        })
        .collect();
    Some(serde_json::json!({
        "what": behaviour.get("what"),
        "stateNote": behaviour.get("stateNote"),
        "hooks": summary,
        "fullExamples": "ui_kit(sections=[\"behaviour\"]) for the markup of each hook",
    }))
}

/// What every reply says about the tile cover recipes.
///
/// Same reasoning as [`behaviour_index`]: the full entries carry markup and
/// sizing prose, so the always-on part is one line per layout — enough to
/// know the vocabulary exists — and `sections=["coverLayouts"]` serves the rest.
fn cover_layouts_index() -> Option<Value> {
    let covers = CONTRACT.get("coverLayouts")?;
    let layouts = covers.get("layouts")?.as_array()?;
    let summary: Vec<Value> = layouts
        .iter()
        .filter_map(|entry| {
            let id = entry.get("id")?.as_str()?;
            let purpose = entry.get("purpose")?.as_str()?;
            Some(Value::String(format!("{id} — {purpose}")))
        })
        .collect();
    Some(serde_json::json!({
        "what": covers.get("what"),
        "layouts": summary,
        "full": "ui_kit(sections=[\"coverLayouts\"]) for markup, animation and sizing notes",
    }))
}

/// What a bare call answers: the map of the contract. One line per section
/// and category, the names of the snippets, and the pointers everything
/// else hangs off. Small enough to read, complete enough to choose from.
fn sections_index() -> Option<Value> {
    let snippets: Vec<&str> = CONTRACT
        .get("snippets")
        .and_then(Value::as_object)
        .map(|map| map.keys().map(String::as_str).collect())
        .unwrap_or_default();
    Some(serde_json::json!({
        "how": "Pass sections (1-4 names below, or a class category) for the full text \
                of those parts, or classes for exact class names. A build starts with \
                ui_kit(sections=[\"coverLayouts\",\"bestPractices\",\"<category>\",\"snippets\"]).",
        "sections": CONTRACT.get("sections"),
        "snippets": snippets,
    }))
}

/// The classes the selected sections serve.
///
/// `all` deliberately serves only smabar's OWN vocabulary plus the category
/// index: the harvested components more than double the reply, and an agent
/// that gets 200 classes it did not ask for stops reading. `classes` is the
/// explicit "give me everything"; a category is the useful middle; the bare
/// index serves none.
fn classes_for(sections: &[String]) -> Option<Value> {
    if sections.is_empty() {
        return None;
    }
    if sections == ["all"] {
        return CONTRACT.get("classes").cloned();
    }
    if sections.iter().any(|section| section == "classes") {
        return Some(Value::Array(CLASSES.clone()));
    }
    if !sections
        .iter()
        .any(|section| CATEGORIES.contains(&section.as_str()))
    {
        return None;
    }
    Some(Value::Array(
        CLASSES
            .iter()
            .filter(|entry| {
                entry["category"]
                    .as_str()
                    .is_some_and(|category| sections.iter().any(|section| section == category))
            })
            .cloned()
            .collect(),
    ))
}

fn selected_sections(
    sections: Option<Vec<String>>,
    has_class_lookup: bool,
) -> Result<Vec<String>, McpError> {
    let lookup_count = usize::from(sections.is_some()) + usize::from(has_class_lookup);
    if lookup_count > 1 {
        return Err(McpError::invalid_params(
            "sections and classes are alternative ui_kit lookups; pass only one".to_string(),
            None,
        ));
    }
    // No sections and no class lookup: the index.
    let Some(selected) = sections else {
        return Ok(Vec::new());
    };
    if selected.is_empty() || selected.len() > MAX_SECTIONS {
        return Err(McpError::invalid_params(
            format!("sections must contain between 1 and {MAX_SECTIONS} entries"),
            None,
        ));
    }
    if selected.len() > 1 && selected.iter().any(|section| section == "all") {
        return Err(McpError::invalid_params(
            "sections cannot combine all with another section; all alone is the complete \
             contract"
                .to_string(),
            None,
        ));
    }
    let unknown: Vec<&str> = selected
        .iter()
        .map(String::as_str)
        .filter(|section| !known(section))
        .collect();
    if !unknown.is_empty() {
        return Err(McpError::invalid_params(
            format!(
                "unknown section(s) {}; expected one of {}, or a class category: {}",
                unknown.join(", "),
                SECTIONS.join(", "),
                CATEGORIES.join(", ")
            ),
            None,
        ));
    }
    Ok(selected)
}

fn classes_named(names: &[String]) -> Result<Value, McpError> {
    if names.is_empty() {
        return Err(McpError::invalid_params(
            "classes must contain at least one exact class name".to_string(),
            None,
        ));
    }
    let mut found = Vec::with_capacity(names.len());
    let mut unknown = Vec::new();
    for name in names {
        match CLASSES
            .iter()
            .find(|entry| entry["name"].as_str() == Some(name.as_str()))
        {
            Some(entry) => found.push(entry.clone()),
            None => unknown.push(name.as_str()),
        }
    }
    if !unknown.is_empty() {
        return Err(McpError::invalid_params(
            format!(
                "unknown UI-kit class name(s): {}; names are exact and omit the leading dot — \
                 use sections=[\"classes\"] or a category section to discover them",
                unknown.join(", ")
            ),
            None,
        ));
    }
    Ok(Value::Array(found))
}

#[tool_router(router = ui_kit_tool_router, vis = "pub(crate)")]
impl SmabarMcp {
    #[tool(
        description = "The markup contract for plugin HTML: sb-* classes, the data-sb-* \
                       behaviour hooks the shell runs for you, icons, charts, the sanitizer \
                       allowlist, conventions (tabs, menus, tooltips, render targets) and \
                       copy-paste snippets. Pass exactly one parameter. `sections`: 1-4 of \
                       bestPractices | coverLayouts | snippets | behaviour | conventions | \
                       sanitizer | media | formContract | branding | renderTargets | tileChrome \
                       | charts | icons | tokens | classes | all, or a class category: actions, \
                       forms, data, content, layout, overlays, feedback, disclosure. `classes`: \
                       exact class names for a small lookup. Without parameters the reply is \
                       the INDEX: one line per section, designRules, tileSizing, \
                       classCategories, the behaviour hooks and the nine cover recipes as \
                       one-liners. Every reply keeps designRules, tileSizing and both indexes; \
                       a named section adds its full text. Riders: forms carries formContract; \
                       data and icons carry charts; content carries media; conventions carries \
                       renderTargets, tileChrome and branding; sanitizer carries media, \
                       formContract and branding. `tokens` is the active theme's resolved \
                       --sb-* map; the machine-readable token contract lives in theme_get. The \
                       first call of a build: ui_kit(sections=[\"coverLayouts\", \
                       \"bestPractices\", \"<category>\", \"snippets\"])."
    )]
    pub(super) async fn ui_kit(
        &self,
        Parameters(UiKitParams {
            sections,
            classes: class_names,
        }): Parameters<UiKitParams>,
    ) -> Result<Json<UiKitResult>, McpError> {
        let targeted = class_names.is_some();
        let sections = selected_sections(sections, targeted)?;
        let served_classes = match class_names {
            Some(names) => Some(classes_named(&names)?),
            None => classes_for(&sections),
        };
        let carries_classes = served_classes.is_some();
        let index_only = sections.is_empty() && !targeted;
        let selected = |name: &str| sections.iter().any(|section| section == name);
        // A key is served when it was named, when `all` was, or when one of
        // the sections it rides with was.
        let wants = |name: &str| {
            !targeted
                && (selected("all")
                    || selected(name)
                    || RIDERS.iter().any(|(key, hosts)| {
                        *key == name && hosts.iter().any(|host| selected(host))
                    }))
        };
        let field = |key: &str| CONTRACT.get(key).cloned();
        Ok(Json(UiKitResult {
            version: CONTRACT.get("version").and_then(Value::as_u64).unwrap_or(1),
            sections: index_only.then(sections_index).flatten(),
            // The design rules lead every reply, whatever section was asked —
            // and so does tileSizing, which they explicitly refer to.
            design_rules: field("designRules"),
            best_practices: wants("bestPractices")
                .then(|| field("bestPractices"))
                .flatten(),
            tile_sizing: field("tileSizing"),
            tokens: wants("tokens")
                .then(|| themes::resolve(&self.paths, &self.config.current().theme)),
            // The 600 KB machine-readable contract belongs to theme_get; here
            // it would bury the markup contract under theme internals.
            token_contract: wants("tokens").then(|| {
                Value::String(
                    "theme_get() — the machine-readable token, settings, schema and \
                     reference-theme contract"
                        .to_string(),
                )
            }),
            classes: served_classes,
            // Whenever classes are served, so is the map of where the rest
            // of them live — and the index carries it as well.
            class_categories: (carries_classes || index_only)
                .then(|| field("classCategories"))
                .flatten(),
            // Every reply carries the index: a hook nobody knows about is a
            // capability nobody can use.
            behaviour: if !targeted && selected("behaviour") {
                field("behaviour")
            } else {
                behaviour_index()
            },
            // Same shape as behaviour: the index everywhere, the full
            // recipes only where asked — a tile designed blind is the most
            // common way a tile ends up ugly.
            cover_layouts: if !targeted && selected("coverLayouts") {
                field("coverLayouts")
            } else {
                cover_layouts_index()
            },
            icons: wants("icons").then(|| field("icons")).flatten(),
            icons_usage: wants("icons").then(|| field("iconsUsage")).flatten(),
            charts: wants("charts").then(|| field("charts")).flatten(),
            sanitizer: wants("sanitizer").then(|| field("sanitizer")).flatten(),
            media: wants("media").then(|| field("media")).flatten(),
            form_contract: wants("formContract")
                .then(|| field("formContract"))
                .flatten(),
            branding: wants("branding").then(|| field("branding")).flatten(),
            conventions: wants("conventions").then(|| field("conventions")).flatten(),
            render_targets: wants("renderTargets")
                .then(|| field("renderTargets"))
                .flatten(),
            tile_chrome: wants("tileChrome").then(|| field("tileChrome")).flatten(),
            snippets: wants("snippets").then(|| field("snippets")).flatten(),
        }))
    }
}
