// @vitest-environment happy-dom
/**
 * Anti-drift tests for the documented class vocabulary.
 *
 * `ui-kit/contract.json` carries smabar's own 63 classes; `ui-kit/
 * kit-classes.json` is GENERATED by `scripts/gen-kit-classes.py` from the
 * format48 manifests the component CSS was harvested from. The MCP `ui_kit`
 * tool serves both as one list, so both have to describe markup that really
 * renders: the class exists in a kit stylesheet, and the example survives the
 * sanitizer.
 */
import { expect, test } from "vitest";

import contract from "../../../ui-kit/contract.json";
import kitClasses from "../../../ui-kit/kit-classes.json";
import harvestedCss from "../styles/kit-components.css?inline";
import kitCss from "../styles/ui-kit.css?inline";
import { sanitizeHtml } from "./sanitize";

/** Both sheets reach a plugin shadow root, so both satisfy the contract. */
const allKitCss = `${harvestedCss}\n${kitCss}`;

function tagSequence(root: ParentNode): string[] {
  return [...root.querySelectorAll("*")].map((el) => el.tagName.toLowerCase());
}

/** Everything the ui_kit tool serves under `classes`: smabar's own
 *  hand-written entries plus the generated harvest documentation. */
const allClasses = [...contract.classes, ...kitClasses.classes];

test("every kit class in the contract exists in the kit stylesheets", () => {
  for (const { name } of allClasses) {
    expect(allKitCss, `class ${name} missing in the kit`).toContain(`.${name}`);
  }
});

test("the form recipe teaches complete labelled fields with examples and hints", () => {
  const root = document.createElement("div");
  root.appendChild(sanitizeHtml(contract.snippets.form));
  expect(root.querySelector("form.sb-stack")).not.toBeNull();
  const fields = root.querySelectorAll<HTMLInputElement | HTMLTextAreaElement>(
    "input, textarea",
  );
  expect(fields.length).toBeGreaterThan(0);
  for (const field of fields) {
    expect(field.closest(".sb-field-stack")).not.toBeNull();
    expect(root.querySelector(`label[for="${field.id}"]`)).not.toBeNull();
    expect(field.placeholder).not.toBe("");
    for (const id of (field.getAttribute("aria-describedby") ?? "").split(
      " ",
    )) {
      if (id !== "") expect(root.querySelector(`#${id}`)).not.toBeNull();
    }
  }
  expect(
    root.querySelector('button[type="submit"][data-action="save"]'),
  ).not.toBeNull();
});

test("the generated class docs are complete and uniquely categorised", () => {
  // scripts/gen-kit-classes.py writes this file; nothing hand-reviews it.
  const categories = new Set([
    "actions",
    "content",
    "data",
    "disclosure",
    "feedback",
    "forms",
    "layout",
    "overlays",
  ]);
  const seen = new Set<string>();
  expect(kitClasses.classes.length).toBeGreaterThan(100);
  for (const entry of allClasses) {
    expect(
      categories.has(entry.category),
      `${entry.name}: ${entry.category}`,
    ).toBe(true);
    expect(entry.purpose.length).toBeGreaterThan(0);
    expect(seen.has(entry.name), `${entry.name} documented twice`).toBe(false);
    seen.add(entry.name);
  }
  // The generator derives every example from real markup, so the class it
  // documents must be visible in it. (Hand-written entries may document an
  // attribute convention instead — sb-carousel's example is data-carousel.)
  for (const entry of kitClasses.classes) {
    expect(entry.example, `${entry.name}'s example omits it`).toContain(
      entry.name,
    );
  }
});

test("every documented class example survives sanitizeHtml structurally", () => {
  // A documented example that the sanitizer prunes teaches markup the shell
  // silently removes — the single worst failure mode of this contract.
  for (const { name, example } of allClasses) {
    const parsed = document.createElement("template");
    parsed.innerHTML = example;
    const before = tagSequence(parsed.content);
    const container = document.createElement("div");
    container.appendChild(sanitizeHtml(example));
    expect(tagSequence(container), `${name} lost elements`).toEqual(before);
  }
});

test("copy component examples keep an actionable shell hook", () => {
  for (const name of ["sb-copy", "sb-code"]) {
    const entry = kitClasses.classes.find(
      (candidate) => candidate.name === name,
    );
    expect(entry, `${name} is undocumented`).toBeDefined();
    const container = document.createElement("div");
    container.appendChild(sanitizeHtml(entry?.example ?? ""));
    const button = container.querySelector<HTMLElement>(".sb-copy");
    expect(button, `${name} has no copy button`).not.toBeNull();
    const selector = button?.dataset.sbCopy;
    expect(
      selector ?? button?.dataset.sbCopyText,
      `${name} has no copy hook`,
    ).toBeTruthy();
    if (selector !== undefined) {
      expect(
        container.querySelector(selector),
        `${name} has no copy target`,
      ).not.toBeNull();
    }
  }
});

test("the category index covers exactly the categories in use", () => {
  // `ui_kit` leaves the harvested classes out of its default reply and hands
  // over this index instead, so a category missing here is unreachable.
  const { note, ...index } = contract.classCategories;
  expect(note).toContain('sections=["classes"]');
  const indexed = new Set(Object.keys(index));
  const used = new Set(allClasses.map((entry) => entry.category));
  expect([...indexed].sort()).toEqual([...used].sort());
  for (const [name, about] of Object.entries(index)) {
    expect(about.length, `${name} has no description`).toBeGreaterThan(20);
  }
});
